build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-debian"
  armhf: "ghcr.io/home-assistant/armhf-base-debian"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian"
  armv7: "ghcr.io/home-assistant/armv7-base-debian"
  i386: "ghcr.io/home-assistant/i386-base-debian"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Crowdsec Firewall Bouncer add-on"
  org.opencontainers.image.description: "Crowdsec bouncer written in golang for firewalls"
  org.opencontainers.image.source: "https://github.com/thywolf/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"